"""CuentaCredito table

Revision ID: 327a2809e0be
Revises: fb4bedb33b67
Create Date: 2018-05-29 14:50:02.197104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327a2809e0be'
down_revision = 'fb4bedb33b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cheques',
    sa.Column('id_Cheque', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Beneficiario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_Cheque')
    )
    op.create_table('CuentaCredito',
    sa.Column('id_Tarjeta_Credito', sa.Integer(), nullable=False),
    sa.Column('Pasivos_Totales', sa.Float(), nullable=False),
    sa.Column('Limite_Credito', sa.Float(), nullable=False),
    sa.Column('Credito_Restante', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_Tarjeta_Credito')
    )
    op.create_table('CuentaInversion',
    sa.Column('id_Cuenta_Inversion', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_Cuenta_Inversion')
    )
    op.create_table('PlanPago',
    sa.Column('id_Plan_Pago', sa.Integer(), nullable=False),
    sa.Column('Fecha_Inicial', sa.String(length=50), nullable=False),
    sa.Column('Fecha_Final', sa.String(length=50), nullable=False),
    sa.Column('Valor_Cuotas', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_Plan_Pago')
    )
    op.create_table('TarjetaDebito',
    sa.Column('id_Tarjeta_Debito', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_Tarjeta_Debito')
    )
    op.create_table('TipoCuenta',
    sa.Column('id_Tipo_Cuenta', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Numero_Cuenta', sa.Integer(), nullable=False),
    sa.Column('Descripcion', sa.String(length=50), nullable=False),
    sa.Column('Saldo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_Tipo_Cuenta')
    )
    op.create_table('divisa',
    sa.Column('id_Divisa', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=50), nullable=False),
    sa.Column('Nomenclatura', sa.String(), nullable=False),
    sa.Column('Relacion_Pesos', sa.Float(precision=50), nullable=True),
    sa.PrimaryKeyConstraint('id_Divisa'),
    sa.UniqueConstraint('Nombre'),
    sa.UniqueConstraint('Nomenclatura')
    )
    op.create_table('gasto',
    sa.Column('Id_Gasto', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Gasto')
    )
    op.create_table('ingreso',
    sa.Column('Id_Ingreso', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Ingreso')
    )
    op.create_table('reembolso',
    sa.Column('Id_Reembolso', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Reembolso')
    )
    op.create_table('CuentaCheques',
    sa.Column('id_CuentaCheque', sa.Integer(), nullable=False),
    sa.Column('Depositar', sa.Float(), nullable=True),
    sa.Column('Retirar', sa.Float(), nullable=True),
    sa.Column('Pagar', sa.Float(), nullable=True),
    sa.Column('Estado', sa.String(length=50), nullable=False),
    sa.Column('id_Cheque', sa.Integer(), nullable=True),
    sa.Column('id_Tarjeta_Debito', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Cheque'], ['Cheques.id_Cheque'], ),
    sa.ForeignKeyConstraint(['id_Tarjeta_Debito'], ['TarjetaDebito.id_Tarjeta_Debito'], ),
    sa.PrimaryKeyConstraint('id_CuentaCheque')
    )
    op.create_table('CuentaPrestamos',
    sa.Column('id_Prestamos', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Float(), nullable=False),
    sa.Column('Periodo', sa.Float(), nullable=False),
    sa.Column('id_Plan_Pago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_Plan_Pago'], ['PlanPago.id_Plan_Pago'], ),
    sa.PrimaryKeyConstraint('id_Prestamos')
    )
    op.create_table('transaccion',
    sa.Column('Id_Transaccion', sa.Integer(), nullable=False),
    sa.Column('Cuenta_Receptor', sa.Integer(), nullable=False),
    sa.Column('Id_Ingreso', sa.Integer(), nullable=True),
    sa.Column('Id_Reembolso', sa.Integer(), nullable=True),
    sa.Column('Id_Gasto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Id_Gasto'], ['gasto.Id_Gasto'], ),
    sa.ForeignKeyConstraint(['Id_Ingreso'], ['ingreso.Id_Ingreso'], ),
    sa.ForeignKeyConstraint(['Id_Reembolso'], ['reembolso.Id_Reembolso'], ),
    sa.PrimaryKeyConstraint('Id_Transaccion')
    )
    op.create_table('presupuesto',
    sa.Column('Id_presupuesto', sa.Integer(), nullable=False),
    sa.Column('Nombre_Presupuesto', sa.String(length=50), nullable=True),
    sa.Column('Monto_Presupuesto', sa.Float(), nullable=False),
    sa.Column('P_Recurrencia', sa.String(length=10), nullable=True),
    sa.Column('Id_Transaccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_Transaccion'], ['transaccion.Id_Transaccion'], ),
    sa.PrimaryKeyConstraint('Id_presupuesto')
    )
    op.create_table('CuentaBancaria',
    sa.Column('id_Cuenta_Bancaria', sa.Integer(), nullable=False),
    sa.Column('id_Divisa', sa.Integer(), nullable=False),
    sa.Column('Patrimonio_Actual', sa.Float(), nullable=False),
    sa.Column('id_Tipo_Cuenta', sa.Integer(), nullable=False),
    sa.Column('Id_presupuesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_presupuesto'], ['presupuesto.Id_presupuesto'], ),
    sa.ForeignKeyConstraint(['id_Divisa'], ['divisa.id_Divisa'], ),
    sa.ForeignKeyConstraint(['id_Tipo_Cuenta'], ['TipoCuenta.id_Tipo_Cuenta'], ),
    sa.PrimaryKeyConstraint('id_Cuenta_Bancaria')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_table('CuentaBancaria')
    op.drop_table('presupuesto')
    op.drop_table('transaccion')
    op.drop_table('CuentaPrestamos')
    op.drop_table('CuentaCheques')
    op.drop_table('reembolso')
    op.drop_table('ingreso')
    op.drop_table('gasto')
    op.drop_table('divisa')
    op.drop_table('TipoCuenta')
    op.drop_table('TarjetaDebito')
    op.drop_table('PlanPago')
    op.drop_table('CuentaInversion')
    op.drop_table('CuentaCredito')
    op.drop_table('Cheques')
    # ### end Alembic commands ###
